easy_admin:
  site_name: 'Blog Cuisine'
  entities:
    User:
      class: App\Entity\User
      role: ROLE_SUPER_ADMIN
    Categories:
      class: App\Entity\Categories
      role: ROLE_SUPER_ADMIN
    Recette:
      class: App\Entity\Recette
      role: ROLE_SUPER_ADMIN
      form:
        fields:
          - title
          - content
          - categories
          - createdAt
          - imageAlt
          - imageSrc
          - nbViews
          - liks
          -
              property: ImageFile
              type: "file"






